description: "dns settings"
source: "Restore to most secure settings"
platforms:
  - android
  - apple
  - linux
localizations:
  ar: "استعادة أكثر الإعدادات أمانًا"
  cs: "Obnovit nejbezpečnější nastavení"
  de: "Sicherste Einstellungen wiederherstellen"
  el: "Επαναφορά στις πιο ασφαλείς ρυθμίσεις"
  en: "Restore to most secure settings"
  es: "Restaurar los ajustes más seguros"
  es-419: "Restaurar la configuración más segura"
  es-MX: "Restaurar la configuración más segura"
  fr: "Rétablir les paramètres les plus sécurisés"
  he: "שחזר להגדרות המאובטחות ביותר"
  hi: "सबसे सुरक्षित सेटिंग्स बहाल करें"
  id: "Pulihkan ke pengaturan paling aman"
  it: "Ripristina le impostazioni più sicure"
  ja: "最も安全な設定に戻す"
  ko: "가장 안전한 설정으로 복원"
  nl: "Veiligste instellingen herstellen"
  pl: "Przywróć najbezpieczniejsze ustawienia"
  pt: "Repor definições mais seguras"
  pt-BR: "Restaurar configurações mais seguras"
  pt-PT: "Repor definições mais seguras"
  ru: "Вернуть самые безопасные настройки"
  sv: "Återställ till säkraste inställningarna"
  sw: "Rejesha mipangilio salama zaidi"
  th: "คืนค่าเป็นการตั้งค่าที่ปลอดภัยที่สุด"
  uk: "Повернути найбезпечніші налаштування"
  vi: "Khôi phục cài đặt an toàn nhất"
  zh: "恢复最安全设置"
  zh-HK: "還原最安全設定"
