description: "Settings"
source: "Update notifications permissions in your Android Settings"
platforms:
  - android
localizations:
  ar: "تحديث أذونات الإشعارات في إعدادات Android"
  cs: "Aktualizace oprávnění k oznámení v nastavení systému Android"
  de: "Benachrichtigungsberechtigungen in deinen Android-Einstellungen aktualisieren"
  el: "Ενημέρωση δικαιωμάτων ειδοποιήσεων στις Ρυθμίσεις Android"
  en: "Update notifications permissions in your Android Settings"
  es: "Actualizar permisos de notificaciones en la configuración de Android"
  es-419: "Actualizar permisos de notificaciones en la configuración de Android"
  es-MX: "Actualizar permisos de notificaciones en la configuración de Android"
  fr: "Mettre à jour les autorisations de notification dans vos paramètres Android"
  he: "עדכן את הרשאות ההתראות בהגדרות האנדרואיד שלך"
  hi: "अपनी Android सेटिंग में सूचना अनुमतियों को अपडेट करें"
  id: "Perbarui izin notifikasi di Pengaturan Android Anda"
  it: "Aggiorna le autorizzazioni per le notifiche nelle Impostazioni Android"
  ja: "Android設定で通知の権限を更新する"
  ko: "Android 설정에서 알림 권한 업데이트"
  nl: "Werk meldingsrechten bij in je Android-instellingen"
  pl: "Zaktualizuj uprawnienia powiadomień w ustawieniach Androida"
  pt: "Atualizar permissões de notificações nas Configurações do Android"
  pt-BR: "Atualizar permissões de notificações nas Configurações do Android"
  pt-PT: "Atualizar permissões de notificações nas Configurações do Android"
  ru: "Обновите разрешения для уведомлений в настройках Android"
  sv: "Uppdatera aviseringsbehörigheter i dina Android-inställningar"
  sw: "Sasisha ruhusa za arifa katika Mipangilio yako ya Android"
  th: "อัพเดตสิทธิ์การแจ้งเตือนบนการตั้งค่า Android ของคุณ"
  uk: "Оновіть дозволи на сповіщення в налаштуваннях Android"
  vi: "Cập nhật quyền thông báo trong Cài đặt Android của bạn"
  zh: "在您的 Android 设置中更新通知权限"
  zh-HK: "請在 Android 設定中更新通知權限"
